### ISSUE TITLE
Percentage labels are all zero in some timeline graphs

### ISSUE THREAD

**Issue by tkent-google** [GoogleChrome/chromium-dashboard#235] opened 2015-09-02 00:34 UTC
Example:  https://www.chromestatus.com/metrics/feature/timeline/popularity/247

Percentage labels on the left side are all '0'.

**Comment by ebidel** [comment] 2015-09-02 01:37
Dupe of https://github.com/GoogleChrome/chromium-dashboard/issues/232

**Closed by ebidel** 2015-09-02 01:37 UTC
