### ISSUE TITLE
CSS Shapes shipped in Opera

### ISSUE THREAD

**Issue by marco-c** [GoogleChrome/chromium-dashboard#265] opened 2016-02-15 10:49 UTC
https://www.chromestatus.com/feature/5163890719588352 should be updated to reflect the Opera status.

**Comment by ebidel** [comment] 2016-02-15 18:14
Dupe of https://github.com/GoogleChrome/chromium-dashboard/issues/263

**Closed by ebidel** 2016-02-15 18:14 UTC

**Comment by marco-c** [comment] 2016-02-15 18:16
@ebidel aren't CSS shapes shipped in Opera?

**Comment by ebidel** [comment] 2016-02-15 18:21
Sorry for not being clear. My point was that the features list and feature panel pages don't call out Opera explicitly. #263 would add Opera to the views.

**Comment by marco-c** [comment] 2016-02-15 18:24
OK, I thought by default when something was marked as shipped in Chrome, it was automatically marked as shipped in Opera as well.

**Comment by ebidel** [comment] 2016-02-15 18:34
Derp. Yea, this one should have already been showing. I've updated the entry and Opera is there now :)

https://www.chromestatus.com/feature/5163890719588352

Thanks for reporting.
