### ISSUE TITLE
Load /features at current stable release instead of "in development" features

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/chromium-dashboard#320] opened 2016-07-12 17:31 UTC
When you load https://www.chromestatus.com/features, it loads at "in development" features.
It may be nicer to land users at the current stable release so it's easier to answer the question "what's available to me"

**Comment by clelland** [comment] 2016-07-12 20:16
As part of #307, I'd definitely like to land users at "the current state of the platform", based on stable. (This being based on all active features in stable, not just those which were added in that release, though)

**Comment by beaufortfrancois** [comment] 2016-07-18 07:47
We may want to add Origin Trials as well. Not only Stable ones.

**Comment by renancleyson-dev** [comment] 2021-03-12 14:46
The issue is stale, and it was assigned to @clelland a long time ago. Can I work on it?

**Comment by vishwjeet-singh** [comment] 2021-03-16 09:24
hi @ebidel, I would like to work on this issue.

**Comment by clelland** [comment] 2021-03-24 16:54
I'm not currently working on this project; @jrobbins is probably the most active right now; that's who I'd check with.

**Comment by VimukthiRandika1997** [comment] 2021-04-03 21:23
Hey!,  @jrobbins

I would like to work with this issue, I am very ego to deal with UI/ UX design as it is passion and it gives me continuous learning curve. So if I have a chance let me know, I do my best. Thanks.

**Comment by GouravSingal-code** [comment] 2021-09-20 09:23
can i work on it

**Comment by arpitghura** [comment] 2022-03-15 04:58
Is this issue currently assigned to someone. If not, I would like to work on this issue.

**Comment by arpitghura** [comment] 2022-03-23 16:00
Hey @ebidel, I would like to work on this issue. please let me know.

**Comment by jrobbins** [comment] 2022-10-06 21:54
This issue is obsolete because the site now has a "roadmap" page as the site homepage.  That answers the question of what new features are available to web developers.    The all-feature is shifting toward only being used when the user is looking for something in particular, so the default query is not too important.

**Closed by jrobbins** 2022-10-06 21:54 UTC
Labels: UX, goodfirstbug
