### ISSUE TITLE
Highlight diffs in notification emails

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#1303] opened 2021-05-03 17:26 UTC
**Is your feature request related to a problem? Please describe.**
It can be hard to see what text changed in an update notification.  The notifications contain old and new text for each field that changed, but the specific words that changed within those field values can be hard to spot.

**Describe the solution you'd like**
We could use an HTML span with a pale red or green background to indicate words that changed.

In cases where the entire text has changed (or maybe over 50%) we can skip highlighting because it would not be too useful. We should try a few different thresholds to see how they work with realistic data.

This could be implemented with python's difflib.  E.g.,
>>> list(difflib.ndiff('hello there , how are you?'.split(), 'hey there , where are you?'.split()))
['- hello', '+ hey', '  there', '  ,', '- how', '+ where', '  are', '  you?']

**Additional context**
Color alone should never be used to convey important information,  so we should keep the Old and New labels.

**Comment by jpmedley** [comment] 2021-05-03 17:33
Making it easier to see what changes will improve the quality of data coming out of Chrome Status. This would be as small change with a big impact.

**Comment by GouravSingal-code** [comment] 2021-09-20 09:21
can i work on it

**Comment by Sonali-Behera** [comment] 2021-11-08 11:47
Hey there! I can handle this issue easily. Please assign this to me.

**Comment by RahulSingh212** [comment] 2021-12-07 04:34
If the issue is still unresolved, I would like to work on this.

**Comment by Vaibhav6200** [comment] 2022-01-25 16:46
I would like to work on this issue, can I work on it?

**Comment by RamGoel** [comment] 2022-06-05 14:29
@jrobbins Can i work on this issue?

**Comment by akhileshappala** [comment] 2023-03-29 04:59
Hi @jrobbins 
As I see this is inactive, Can you please assign it to me? I am trying to contribute to the dashboard project for GSOC 2023

**Comment by syedbarimanjan** [comment] 2024-02-22 13:20
@jrobbins @DanielRyanSmith I would like to work on this. Can I use JavaScript/TypeScript instead of Python, considering it is for the web, and they are well-suited for the task.

**Comment by Rishikesh63** [comment] 2024-02-25 05:59
@jrobbins & @DanielRyanSmith I would like to work on it.                                                                                                                                                                                                    using difflib module we can write a function that will print the old and new text with highlighted changes using HTML spans with red background for deletions and green background for additions. It also considers a threshold for significant changes, beyond which the entire text is shown without highlighting. we can adjust the threshold value as needed to suit our requirements.

**Comment by impact-maker** [comment] 2024-02-26 05:36
Hi @DanielRyanSmith  @jrobbins  I have proposed an initial draft for the issue by adding a highlight difference colour code function. I have completed the setup and working on the CLA , meanwhile could you provide me some feedback on my proposed function .

Proposed Solution 
#3671

**Closed** 2024-03-19 21:27 UTC
Labels: enhancement, goodfirstbug
