### ISSUE TITLE
Roadmap shows 117 twice / 118 is missing

### ISSUE THREAD

**Issue by TheDet** [GoogleChrome/chromium-dashboard#3395] opened 2023-10-09 08:56 UTC
Currently  https://chromestatus.com/roadmap presents   117  as  Released as well as Stable,  and 119 as NextUp.
Chrome 118 is missing (I suppose this should be presented as Stable?).

**Comment by jrobbins** [comment] 2023-10-09 22:16
The underlying problem is that we show the versions on each channel (stable, beta, and dev) as the initial content for that page, however today stable=117 and beta=119, meaning that 118 is in a gap between the two channels.   I am not sure what the cause of that is, but that is the data that we get from our data sources.

I have a partial fix live on the site now.  It displays 118 under a "Stable soon" heading.  But, the date at which it was supposed to start going out to the stable channel has already passed, so there's an awkward combination of future and past tense wording.

I have not looked into why 117 appears twice yet.  I think that is just an off-by-one error in our code where it fails to handle this kind of gapped situation.

**Comment by DanielRyanSmith** [comment] 2024-01-08 18:50
Can this be closed after your landed change @jrobbins?

**Comment by jrobbins** [comment] 2024-01-08 21:57
Yep, all done.

**Closed by jrobbins** 2024-01-08 21:57 UTC
Labels: bug
