### ISSUE TITLE
Cannot set Blink>URLPattern as bug component.

### ISSUE THREAD

**Issue by wanderview** [GoogleChrome/chromium-dashboard#1431] opened 2021-07-22 17:19 UTC
In this feature:

https://chromestatus.com/feature/5731920199548928

I need to use `Blink > URLPattern` as the bug component, but its not an option in the drop down.  I assume this drop down just has a snapshot of some past set of components.  Can it be updated?

**Comment by jpchase** [comment] 2021-08-13 15:41
Likely duplicate of #496 or #565. Short version is that the list of components available for selection is not the full list of components in crbug.

Looks like there's been a number of recent reports of the issue. Maybe update the UI to add note that this is a known issue to avoid confusion and more bug reports.

**Comment by jpmedley** [comment] 2021-12-16 21:05
@jpchase this is not *exactly* a duplicate of those tickets. Right now the process for updating components to match monorail is manual and we often don't know unless someone tells us that we're missing one. (Sorry for the noise if you've heard that already.)

This particular one is in the app now. Closing.

**Closed by jpmedley** 2021-12-16 21:05 UTC
Labels: bug
