### ISSUE TITLE
"Email owners" feature

### ISSUE THREAD

**Issue by maxh** [GoogleChrome/chromium-dashboard#77] opened 2013-10-15 22:19 UTC
Much of the data on chromestatus.com goes stale after it's used for "intent" threads.

Should we send out a bi-monthly email to feature owners asking them to update their features?  The email would basically say "here's the current information for your feature....  if this is wrong, please update it [here]."

WDYT?

**Comment by RByers** [comment] 2016-07-08 15:37
I agree this seems like a great idea, but lowering to P2.

**Comment by RByers** [comment] 2016-07-14 19:42
There's a disabled checkbox on the feature entry page that says: "e-mail owners when this feature is updated".  I assume it's disabled because it's never actually worked?  I've certainly never seen such an e-mail.  I'd argue we should just do that by default.  Being notified of updates is more valuable than a regular ping IMHO.  

@ebidel @drufball WDYT?

**Comment by ebidel** [comment] 2016-07-14 21:22
Correct, we never implemented it. It should have been removed from the UI.

Unless folks think it'll be spammy, emailing by default seems 👍

**Comment by jpmedley** [comment] 2018-01-11 17:06
Now that we have a mechanism to email interested parties when a feature is created or updated, can we just add the owners to the cc list? It doesn't look like we're doing that now.

This seems pretty easy. If you agree, assign me and I'll take care of it.

**Comment by ebidel** [comment] 2018-01-11 17:09
Good idea.

**Comment by jpmedley** [comment] 2020-03-11 15:38
This is a duplicate of #598. Though newer, that bug is more specific about what needs to be done.

**Closed by jpmedley** 2020-03-11 15:38 UTC
Labels: P1, enhancement
