### ISSUE TITLE
Show Chrome Android features in feature "launches"

### ISSUE THREAD

**Issue by mounirlamouri** [GoogleChrome/chromium-dashboard#417] opened 2016-10-04 10:19 UTC
STR:
* Go to https://www.chromestatus.com/feature/6406908126691328
* see it's enabled by default in M55 on Chrome Android
* Go to chromestatus.com
* Click on "55 canary/dev"
* Look at entries

Actual result: the entry does not appear
Expected result: the entry should appear

**Comment by mdittmer** [comment] 2016-10-04 14:02
Glad I got nagged to fix this. This is a duplicate of #409. Hoping to push a fix today.

**Closed by mdittmer** 2016-10-04 14:02 UTC

**Comment by mdittmer** [comment] 2016-10-04 14:49
Allow me to qualify my previous statement: Even when a fix for #409 lands, this feature won't appear when clicking "55 canary/dev" because it has no Chrome (desktop) shipped_milestone, only a shipped_android_milestone. Presently, search doesn't support disjunction, so the easy fix of making links point to "shipped_milestone=55 or shipped_opera_milestone=55 or shipped_android_milestone=55" is harder to implement than it sounds.
