### ISSUE TITLE
Integrate with Firefox platform status

### ISSUE THREAD

**Issue by RByers** [GoogleChrome/chromium-dashboard#294] opened 2016-07-11 15:25 UTC
Like for #114 and #288 but for https://platform-status.mozilla.org/

**Comment by ebidel** [comment] 2016-07-11 16:39
Dupe of https://github.com/GoogleChrome/chromium-dashboard/issues/224

**Closed by ebidel** 2016-07-11 16:39 UTC

**Comment by RByers** [comment] 2016-07-11 21:20
Whoops, sorry - not sure why I didn't find it when I searched.
