### ISSUE TITLE
Too many feature change diffs

### ISSUE THREAD

**Issue by jrobbins** [GoogleChrome/chromium-dashboard#2425] opened 2022-11-01 22:49 UTC
**Describe the bug**
A user reported getting a feature change notification that had a diff for creator going from "None" to their email address.  That should not have happened because this was an existing feature, so the creator should have already been set and not changed.

https://screenshot.googleplex.com/C8h42ZdBbewSxpR

**Comment by DanielRyanSmith** [comment] 2022-11-28 22:53
After taking a look at this, we do have a number of old Feature entities (and by extension FeatureEntry entities) that had never had their `created_by` or `creator` fields written, so I'm first inclined to think this is related to that. I'll keep an eye out to see if more of these strange amendment instances occur and try to find the cause.

**Comment by DanielRyanSmith** [comment] 2023-03-16 22:14
This has been fixed in production for a while now, but I still keep an eye on it just in case there is a regression somewhere. I'm closing this for now and I'll update if anything changes.

**Closed by DanielRyanSmith** 2023-03-16 22:14 UTC
Labels: bug
