### ISSUE TITLE
Database update doesn't seem to take right away after Submitting new issue

### ISSUE THREAD

**Issue by dtapuska** [GoogleChrome/chromium-dashboard#397] opened 2016-08-24 19:21 UTC
I tried to file a new feature and because it didn't seem like it worked the first time. After I hit submit my feature did not appear in the feature list.

I refreshed and it still did not appear. So I created it again and it didn't appear again. When I was then showing it to @RByers for the third time all three appeared.

It sounds related to issue https://github.com/GoogleChrome/chromium-dashboard/issues/389 where the database seems not to be getting updated right away.

Can someone please remove the "Remove Me" duplicates in this list:
[https://www.chromestatus.com/features#Event Listeners](https://www.chromestatus.com/features#Event Listeners)

**Comment by ebidel** [comment] 2016-08-24 20:39
Yea, seems like a dupe of https://github.com/GoogleChrome/chromium-dashboard/issues/389. 

I've removed the dupes: https://www.chromestatus.com/features#remove me

Let's continue the convo over there.

**Closed by ebidel** 2016-08-24 20:39 UTC
