### ISSUE TITLE
Opening a feature counter in a new background tab does not select the feature in the list

### ISSUE THREAD

**Issue by phistuck** [GoogleChrome/chromium-dashboard#203] opened 2015-05-09 09:58 UTC
For example, middle click on https://www.chromestatus.com/metrics/feature/timeline/popularity/679 and wait for it to finish loading. Now, go to the tab.
While the graph is correct, the selection box shows "AddEventListenerNoArguments" instead of "WhiteSpacePreFromXMLSpace".
Reloading the page, while the tab is not in the background, will select the right feature.

**Comment by ebidel** [comment] 2015-08-04 16:01
Likely related: 
https://github.com/GoogleChrome/chromium-dashboard/issues/203
https://github.com/GoogleChrome/chromium-dashboard/issues/120

**Comment by RByers** [comment] 2016-07-08 15:49
Yeah this is a dupe of #220

**Closed by RByers** 2016-07-08 15:49 UTC
