### ISSUE TITLE
Draft Email for Intent to Deprecate is broken

### ISSUE THREAD

**Issue by dadrian** [GoogleChrome/chromium-dashboard#3853] opened 2024-05-06 22:59 UTC
**Describe the bug**
Clicking the "Draft Intent to Deprecate" email button throws Javascript console error.

**To Reproduce**
1. Go to 'My feature -> "Feature"'
1. Scroll down to 'Development Stages'
1. 2. Click on 'Draft Intent to Deprecate'
1. See error.  If applicable, add screenshots to help explain your problem.

```
chromedash-preflight-dialog.js:47 Uncaught TypeError: Cannot read properties of undefined (reading 'filter')
    at findPendingGates (chromedash-preflight-dialog.js:47:38)
    at somePendingGates (chromedash-preflight-dialog.js:43:10)
    at ChromedashFeatureDetail.checkCompletion (chromedash-feature-detail.js:557:9)
    at I.handleEvent (lit-html.js:2068:29)
```

<img width="892" alt="Screenshot 2024-05-06 at 3 55 38 PM" src="https://github.com/GoogleChrome/chromium-dashboard/assets/1158264/253c74ac-3608-4ba0-bc96-2abf6b71e504">

**Expected behavior**
A draft email is generated.

**Comment by jrobbins** [comment] 2024-05-07 18:05
I can repro this on some deprecation feature entries on staging.

I think the root cause is that in #3659 I added gates and this action to this stage, but we did not backfill gates on existing feature entries.  That by itself is OK because the feature owners of existing deprecation feature entries could continue to generate these emails by hand like they were doing before my PR.  For those old feature entries, the action button to generate the email would not have been displayed anywhere because the gate that it was part of did not exist on those feature entries.

However, the button became visible to users after #3773 merged.  That PR displays buttons for actions on stages that have no gates.  It should not display this button because that stage should have gates.

Possible solutions:
* BEST: Backfill gates on the plan stage of old deprecation feature entries
* Add logic to not show this particular action button even though it looks like a gate-less stage action.
* Allow the owners of old deprecations to generate the email without gates, which would be a confusing mix of old and new processes.

**Comment by jrobbins** [comment] 2024-05-07 18:46
I backfilled the gates on staging and prod.

You should now see gates for Enterprise, Debuggability, Testing, and API Owners.   The button to generate the email is now part of the API Owners gate and it should work.

![image](https://github.com/GoogleChrome/chromium-dashboard/assets/17365/8253d82b-1124-43b3-8143-3ee85644d19e)


There is also a coding error in the case where there is a legitimate gate-less action, for example "Draft Ready for Developer Testing email".  I will send a PR for a fix, and try to get it into our next release.

**Closed** 2024-05-07 19:20 UTC
Labels: bug
