### ISSUE TITLE
JS metrics page throwing 500

### ISSUE THREAD

**Issue by ebidel** [GoogleChrome/chromium-dashboard#653] opened 2019-06-21 08:27 UTC
https://chromestatus.com/metrics/feature/popularity is not returning data. Looks like the data endpoint (https://chromestatus.com/data/featurepopularity) is returning a 500.

The logs will probably reveal what's going on.

Could be related: https://github.com/GoogleChrome/chromium-dashboard/issues/519

**Comment by jpmedley** [comment] 2019-06-21 18:00
This appears to be an intermittent error.

**Comment by jrobbins** [comment] 2019-10-31 18:43
This is a duplicate of #678.

**Closed by jrobbins** 2019-10-31 18:43 UTC
Labels: duplicate
