### ISSUE TITLE
Navigating to All Features closes the hamburger menu

### ISSUE THREAD

**Issue by past** [GoogleChrome/chromium-dashboard#3167] opened 2023-07-14 13:20 UTC
After the new UI changes switching to a different tab works as expected, leaving the left menu open to select another tab to navigate to. The only exception is https://chromestatus.com/features, which immediately closes the menu on navigation.

**Comment by past** [comment] 2023-07-14 13:23
https://chromestatus.com/newfeatures doesn't have the same issue.

**Comment by jrobbins** [comment] 2023-07-14 15:11
The cause is that the open/close state is not stored anywhere, so as soon as we do a MPA page transition we lose that state and just show the default.  It had been open by default on the MPA pages, but the menu overlapped the content, so we went with closed by default on MPA pages.

I'll try to fix the overlap so that it can be open by default on both SPA and MPA pages on desktop.

**Closed** 2023-07-27 01:50 UTC
Labels: bug
