### ISSUE TITLE
implement Eng elements to align with Material design style

### ISSUE THREAD

**Issue by carolrivero** [GoogleChrome/chromium-dashboard#739] opened 2020-02-06 19:44 UTC

**Comment by jrobbins** [comment] 2020-07-23 20:06
The design doc is at
https://docs.google.com/document/d/1uF79Pk-UeD1DSpDvp5DPyMnVmDJi1ZwqkOcuqW5vVT4/edit#

**Comment by jrobbins** [comment] 2020-08-18 20:39
This is a duplicate of #926.

**Closed** 2020-08-18 20:39 UTC
Labels: Epic
