### ISSUE TITLE
Some fields visible in the Edit view are not visible in the View view

### ISSUE THREAD

**Issue by mgiuca** [GoogleChrome/chromium-dashboard#937] opened 2020-07-29 00:17 UTC
**Describe the bug**
I recall filing this bug over a year ago but I can't find it now (did this move to GitHub since then?)

When editing an item, there are lots and lots of fields. But in the view display that everybody sees, not all of those fields are visible. I recall last time I investigated this deeply, the set of fields visible in the view mode are dependent on the feature's status, which is really unintuitive. It makes it very hard to expose information so that people can actually see it.

Case in point: I was looking for the explainer for Window Placement:
* https://www.chromestatus.com/features/5252960583942144 (overview)
* https://www.chromestatus.com/feature/5252960583942144 (details)

It isn't visible anywhere on either page. But if you have Edit permission, you can go into the dashboard and see that the Explainer link has been correctly filled in. It just isn't exposed.

Please make sure all fields that have a value are exposed unconditionally.

**To Reproduce**
1. Create a feature.
2. Set Intent stage to "start prototyping".
3. Enter a valid URL in "Explainer link(s)".

**Expected behavior**
Explainer link is visible on both pages.

**Additional context**
If ALL fields is too much information to expose on the summary page, it should at least be visible on the details page (though note that I didn't even realise there was a details page until I got halfway through filing this bug... make that much easier to find by having a "more details" link at the bottom of each entry).

Or, simply ask for less information on the Edit view. I've filled out this form many times, and it takes a LONG time to answer all of those questions. It's quite demoralizing to realise once you submit it that almost all of the data you entered will never be seen by anybody. Just remove the fields that you don't expose, so that I don't have to fill them in.

**Comment by michaelwasserman** [comment] 2020-07-29 00:25
I'll put the explainer link in the "Doc link(s)" field for now... thanks for pointing out this chromestatus issue!

**Comment by jstenback** [comment] 2020-07-29 20:50
For context, there's a number of pieces of information that is collected by the chromestatus.com tool that is not displayed when you go view an entry. Whether right or wrong, that is by design, as a bunch of the information is only collected for the purposes of feeding into the template generation that the tool does for "Intent to *" messages, and are primarily only relevant there, as part of the Blink launch process.

The fact that we don't show the explainer links anywhere one can certainly argue is a bug, as that is a piece of information that is relevant to an audience broader than the launch process.

If it is the case that some of the information that is collected here is truly never used anywhere, then that is something we should look into. Also worth noting that there's a significant rewrite of the editing UI underway, as is visible behind the "Try new UI" links on the editing pages.

**Comment by mgiuca** [comment] 2020-08-17 06:34
I have also found the vice versa case is true.

I was upgrading [Digital Goods API](https://chromestatus.com/admin/features/edit/5339955595313152) to an origin trial with the intention of generating an Intent to experiment email.

Nowhere in the edit page (in either the old or new UI) can I see any way to edit the public vendor signals. But the vendor signals shows up in both the [public view](https://chromestatus.com/features/5339955595313152) and in the generated email. How do I edit this field? I suspect I need to find the right status in the dropdown, which will cause those fields to show up in the edit view, then I can edit them, and change the status back to what I want. I recall having to do that before.

Why doesn't it just let me edit all the fields all the time?

**Comment by mgiuca** [comment] 2020-10-27 23:43
I just hit this again for https://www.chromestatus.com/feature/5263213807534080

We've correctly entered the Explainer link, but there is no way to find this link (the main link to learn more about this API) for a casual observer.

Rather than tackling the whole problem, could we just make Explainer links always visible regardless of the intent stage? That seems to be the main missing field.

**Comment by jpmedley** [comment] 2020-11-02 16:22
Matt,

I apologize for not following up on this.

Gang, here's the issue he opened. Can we get this on our schedule?

https://github.com/GoogleChrome/chromium-dashboard/issues/937

Joe
Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by jrobbins** [comment] 2020-11-02 19:14
Sorry to let this slide.  I will get back to working on it today.

**Comment by jrobbins** [comment] 2021-03-12 22:54
This was addressed in 87d0364022fd350a62c7c4663169980b0a7d5e56 and some subsequent commits.

All fields of the feature entry are now shown when you click the "Additional fields by process phase" section title.  The explainer link is there as part of the "Start incubating" stage.

**Closed by jrobbins** 2021-03-12 22:54 UTC
Labels: Feedback, bug
