### ISSUE TITLE
Automatically link to blink intent threads?

### ISSUE THREAD

**Issue by RByers** [GoogleChrome/chromium-dashboard#370] opened 2016-07-27 15:10 UTC
Searching through some deprecation/removals I found it was a little awkward to go from a list in chromestatus to the intent threads.  I was going to suggest including the intent thread URL as a new field, but maintaining that could be a bit of a PITA.  What about having chromestatus somehow automatically link to any blink-dev threads that reference the specific chromestatus URL?   That would be super handy, and also help clarify the status of a feature.

**Comment by RByers** [comment] 2017-08-24 17:06
It looks like this could be done trivially by including a link to a blink-dev search for the feature ID, eg. [recent intent](https://groups.google.com/a/chromium.org/forum/#!searchin/blink-dev/5733828735795200%7Csort:relevance) for the ["CORS restrictions on internet-to-intranet connections" feature](https://www.chromestatus.com/feature/5733828735795200).  @ebidel WDYT?

**Comment by ebidel** [comment] 2017-08-24 17:22
Good find! Very easy :)

**Comment by jpmedley** [comment] 2021-02-25 16:31
Typical procedure would be to mark the newer issue as duplicate. However the one created by the current crew is are linked in a number of artifacts related to current plans. 

Duplicate of #1172

**Closed by jpmedley** 2021-02-25 16:31 UTC
Labels: duplicate
