### ISSUE TITLE
Make features machine-readable

### ISSUE THREAD

**Issue by jyasskin** [GoogleChrome/chromium-dashboard#2585] opened 2022-12-15 00:44 UTC
**Is your feature request related to a problem? Please describe.**

I'd like to use feature URLs like https://chromestatus.com/feature/6577673212002304 as the identity of a feature, and then extract information from them in spreadsheets. Unfortunately, `curl https://chromestatus.com/feature/6577673212002304`, and the similar operation done by spreadsheet functions like [`IMPORTXML()`](https://support.google.com/docs/answer/3093342), doesn't see any of the actual data.

**Describe the solution you'd like**

Either have the feature page link to a machine-readable expression of its content, or [render the content to light-DOM server-side](https://lit.dev/docs/ssr/overview/) so that an XPath expression can find important fields.

**Comment by jpmedley** [comment] 2022-12-15 16:54
Duplicate of #2050

**Closed by jpmedley** 2022-12-15 16:54 UTC
Labels: enhancement
