### ISSUE TITLE
edit icon not showing

### ISSUE THREAD

**Issue by AsedAliSekh** [GoogleChrome/chromium-dashboard#3648] opened 2024-02-06 15:02 UTC
https://github.com/GoogleChrome/chromium-dashboard/blob/8ecb3c92f6b5588c9202370abf6c635568a86bf8/client-src/elements/chromedash-all-features-page.js#L94

**Comment by BalrajDhakad** [comment] 2024-02-23 13:55
I am willing to work on this issue can you please elaborate it to me

**Comment by BalrajDhakad** [comment] 2024-02-23 13:56
@AsedAliSekh

**Comment by DanielRyanSmith** [comment] 2024-02-28 23:10
Duplicate of #3569

**Closed** 2024-02-28 23:10 UTC
