### ISSUE TITLE
No sample URLs on 4057

### ISSUE THREAD

**Issue by davidsgrogan** [GoogleChrome/chromium-dashboard#1781] opened 2022-03-08 21:40 UTC
https://chromestatus.com/metrics/feature/timeline/popularity/4057 was added about 6 months ago but doesn't have any Sample URLs. Will they be filled in later? If so, when?
<img width="904" alt="Screen Shot 2022-03-08 at 1 37 53 PM" src="https://user-images.githubusercontent.com/1801875/157329650-33af258c-4ebe-4c60-aa35-593b0389c38b.png">

**Comment by mfreed7** [comment] 2022-04-12 17:55
Related to https://github.com/GoogleChrome/chromium-dashboard/issues/1814?

Maybe not, but feels oddly similar.

**Comment by past** [comment] 2022-04-15 21:07
Fixed by https://github.com/WPO-Foundation/wptagent/pull/468 and the subsequent March crawl.

**Comment by jrobbins** [comment] 2022-05-03 01:02
Yes, I think this was caused by the same problem as #1814.   That fix when live a while ago.  I see sample URLs on the linked page when I look now.

**Closed by jrobbins** 2022-05-03 01:02 UTC
Labels: bug
